spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true    #开启从注册中心动态创建路由，利用微服务进行路由
      routes:
        - id: payment_routh     #路由的ID，没有固定规则但要求唯一
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/{segment},false    #路径符合的进行路由
#            - Cookie=username,tllt
#            - Host=**.tllt.com,**.cmbchina.com
        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
              - Path=/payment/timeout

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka

server:
  port: 9090