server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/tllt_1/springcloud-config.git #git仓库中clone的地址
          username: 13108930454  # 私有仓库需要加上账号和密码
          password: t1998528721
      #读取分支
      label: master
eureka:
  client:
    server-url:
      defaultZone: http:localhost:7002/eureka



