server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka

#spring:
#  application:
#    name: cloud-order-service


#feign:
#  client:
#    config:
#      feignName:
#        connectTimeout: 5000
logging:
  level:
     com.tllt.springcloud.service.PaymentOpenFeignService: debug
#        readTimeout: 5000